/*
 * Copyright 2022-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.ktorm.ksp.annotation

import org.ktorm.schema.SqlType
import kotlin.reflect.KClass

/**
 * Specify the mapped column for an entity property. If no `@Column` annotation is specified, the default values apply.
 */
@Target(AnnotationTarget.PROPERTY)
@Retention(AnnotationRetention.SOURCE)
public annotation class Column(

    /**
     * The name of the column.
     *
     * If not specified, the name will be generated by a naming strategy. This naming strategy can be configured
     * by KSP option `ktorm.dbNamingStrategy`, which accepts the following values:
     *
     * - lower-snake-case (default): generate lower snake-case names, for example: userId --> user_id.
     *
     * - upper-snake-case: generate upper snake-case names, for example: userId --> USER_ID.
     *
     * - Class name of a custom naming strategy, which should be an implementation of
     * `org.ktorm.ksp.spi.DatabaseNamingStrategy`.
     */
    val name: String = "",

    /**
     * The SQL type of the column.
     *
     * If not specified, the SQL type will be automatically inferred by the annotated property's Kotlin type.
     * The specified class must be a Kotlin singleton object or a normal class with a constructor that accepts a single
     * [org.ktorm.schema.TypeReference] argument.
     */
    val sqlType: KClass<*> = SqlType::class,

    /**
     * The name of the corresponding column property in the generated table class.
     *
     * If not specified, the name will be the annotated property's name. This behavior can be configured by KSP option
     * `ktorm.codingNamingStrategy`, which accepts an implementation class name of
     * `org.ktorm.ksp.spi.CodingNamingStrategy`.
     */
    val propertyName: String = "",
)
